### ISSUE TITLE
Cannot read/write nested fragments

### ISSUE THREAD

**Issue by johannesbraeunig** [dotansimha/graphql-code-generator-community#140]
<details>
<summary>Versions</summary>

Versions
- @graphql-codegen/add@3.0.0
- @graphql-codegen/cli@2.0.1
- @graphql-codegen/near-operation-file-preset@2.0.0
- @graphql-codegen/plugin-helpers@2.0.0
- @graphql-codegen/typed-document-node@2.0.0
- @graphql-codegen/typescript@2.0.0
- @graphql-codegen/typescript-graphql-files-modules@2.0.0
- @graphql-codegen/typescript-operations@2.0.1

</details>

**Describe the bug**

In our project, we create a new GraphQL file for each query, mutation, and fragment. Out of that, a types file is generated, including the GraphQL document.

We're making use of the Apollo write/read fragment feature, in order to store some state in the Apollo cache or simply overwrite some data. For this, we use the document of the fragment from the generated types file.

With the latest update, we get an error, that no fragment was found for a specific name. We looked a bit deeper into that and found out, for fragments that import another fragment, the fragment is not included in the respective document.

```graphql
fragment Zip on Zip {
   zip
}
```

```graphql
#import "./zip.fragment.gql"
fragment Address on Address {
   street
   zip {
     ...Zip
   } 
}
```

```typescript
import { AddressFragmentDoc } from './address.fragment.gql-types.tsx';

client.writeFragment({
   fragment: AddressFragmentDoc,
   data: {
      // the data
   }
})
```

This causes the following error: ` Invariant Violation: No fragment named Zip.`

Looking into the changes of our current upgrade PR, we can see that for all **fragments** that all `fragment.definitions` assignments to the document got removed, while they been added to the respective query and mutations.

Example:
```diff
export const AddressFragmentDoc = {
  kind: 'Document',
  defintions: [
    {
       // the current fragment document defintion
    }
-    ...ZipFragmentDoc.definitions
  ]
}
```

It seems, by removing the definitions of the imported fragment we lose the information about the fragment.

### Questions
- is this a bug?
- is there any configuration around this issue?

**Comment by dkarten** [comment]
Have just run into this as well. Are there any updates on a forthcoming fix or better workarounds?

**Comment by erikwrede** [comment]
I believe the issue with `dedupeFragments` `typed-document-node` codegen in general is, that the `MyFragmentDoc`s are re-used in the in the executable `OperationDefinition`s. That way, it isn't possible to have the fragments include the nested fragments when using `dedupeFragments`. Instead, the fragments would need to be generated as Standalone Fragments, including the dependencies.

However, it is mentioned in the main repo, that `dedupeFragments` is deprecated:

https://github.com/dotansimha/graphql-code-generator/blob/6b6fe3cbcc7de748754703adce0f62f3e070a098/packages/plugins/other/visitor-plugin-common/src/base-visitor.ts#L342-L350

Does that mean, that in the future everyone will run into this problem, or is there now another way around `dedupeFragments`?

**Comment by n1ru4l** [comment]
@erikwrede See https://github.com/dotansimha/graphql-code-generator/pull/8971

The `dedupeFragments` option was broken by design and in the latest release we default to always inline definitions to avoid the limitations.

**Comment by erikwrede** [comment]
@n1ru4l thanks for the quick reply! Please excuse the confusion and using this thread to ask, but which version of codegen do I need to use to try this out? I'm on `graphql-codegen/cli`, but the PR says the release is in `graphql-cli/codegen` - however, I can't find it in any of the release notes.

**Comment by n1ru4l** [comment]
@erikwrede `@graphql-codegen/visitor-plugin-common@3.0.1`, see the changelog: https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1676995873

**Comment by erikwrede** [comment]
Can confirm that this is fixed now, thanks for the help! ☺️

**Comment by n1ru4l** [comment]
Cool, I am going to close this issue then. 🥳

**Comment by adrienharnay** [comment]
Hello @n1ru4l, thank you for the fix that seems to work on my side too (I need to test more). However, it seems fragments are still imported even if they are not used, which results in TS errors. Is this an oversight in the refactoring or something I'm doing wrong?

**Comment by erikwrede** [comment]
Interesting, I don't observe this behavior. Have you got an example @adrienharnay?

**Comment by adrienharnay** [comment]
Yes @erikwrede , here you go: https://codesandbox.io/s/gql-code-generator-without-dedup-fragments-forked-35lp34?file=/src/user.fragment.generated.tsx

Run `yarn codegen` and check the `user.fragment.generated` file and you will see an unused import of `AddressFragmentDoc`

**Comment by n1ru4l** [comment]
@adrienharnay Please open a new issue for this, can you help fixing it?

**Comment by adrienharnay** [comment]
Hi @n1ru4l, I just created the issue: https://github.com/dotansimha/graphql-code-generator-community/issues/289. I can help fixing it but would need the help of the person who did the refactoring I guess?

**Comment by thexpand** [comment]
I don't see how this is fixed. I am still getting the `$fragmentRefs` after the update.

**Comment by adrienharnay** [comment]
Hi @n1ru4l , I opened a PR: https://github.com/dotansimha/graphql-code-generator/pull/9136

**Comment by dwknippers** [comment]
> I don't see how this is fixed. I am still getting the `$fragmentRefs` after the update.

Running into the same issue, seems to be purely typescript related e.g.
```
(property) IItem:item {
    ' $fragmentRefs'?: {
        ItemFragment: ItemFragment;
    } | undefined;
}
(property) IHeader.item: {
    ' $fragmentRefs'?: {
        ItemHeaderFragment: ItemHeaderFragment;
    } | undefined;
}
```
_Note_: the item `fragmentRefs` should contain the fragment type of the sub header fragment.

This is using `client-preset` with React `useFragment` as described in documentation.

A workaround is using an explicit cast e.g. `item as FragmentType<typeof ItemHeaderFragment>`

**Comment by akin-fagbohun** [comment]
> > I don't see how this is fixed. I am still getting the `$fragmentRefs` after the update.
> 
> Running into the same issue, seems to be purely typescript related e.g.
> 
> ```
> (property) IItem:item {
>     ' $fragmentRefs'?: {
>         ItemFragment: ItemFragment;
>     } | undefined;
> }
> (property) IHeader.item: {
>     ' $fragmentRefs'?: {
>         ItemHeaderFragment: ItemHeaderFragment;
>     } | undefined;
> }
> ```
> 
> _Note_: the item `fragmentRefs` should contain the fragment type of the sub header fragment.
> 
> This is using `client-preset` with React `useFragment` as described in documentation.
> 
> A workaround is using an explicit cast e.g. `item as FragmentType<typeof ItemHeaderFragment>`

Instead of casting, I was able to work around this by importing the `FragmentDoc` from the generated types and pairing that with the codegen generated `useFragment` hook.

So where I was doing

`const SomeInaccessibleData = data.SomeInaccessibleData as SomeInaccessibleFragment;`

I'm now doing

```
import { SomeInaccessibleBehindFragmentDoc } from ./generated-types-location;
import { useFragment } from ./generated-fragment-masking-file;

...

const someInaccessibleData = useFragment(SomeInaccessibleBehindFragmentDoc, data.someInaccessibleData);

...
```

**Comment by akin-fagbohun** [comment]
I was able to work through this a different way to @dwknippers by using the codegen generated `useFragment` helper (not hook).

Where I was casting as they recommended above with...

`const someInaccessibleData = data.someInaccesibleData as SomeInaccessibleFragment`

I'm now doing

```
import { SomeInaccessibleFragmentDoc } from './generated-types-location' // not the Fragment, but the FragmentDoc
import { useFragment } from './generated-fragment-types-location'

...

const someInaccessibleData = useFragment(SomeInaccessibleFragmentDoc, data.someInaccessibleData)
```

Your linter might then complain about what appears to be a `use` hook, however codegen have notes on this within their docs and provide a work-around [here](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#the-usefragment-helper:~:text=useFragment()%20is%20not%20a%20React%20hook)

After making the recommended change to the `useFragment` naming convention, I end up with `const someInaccessibleData = getFragmentData(SomeInaccessibleFragmentDoc, data.someInaccessibleData)` and have access to the types from the fragment where they were previously out of reach.

Hopefully that helps someone...
