### ISSUE TITLE
Urql option to invalidate query on each mutation

### ISSUE THREAD

**Issue by namnm** [dotansimha/graphql-code-generator-community#166]
**Is your feature request related to a problem? Please describe.**
On each mutation, the data will be changed, we usually need to manually call invalidate to trigger refetch: https://formidable.com/open-source/urql/docs/graphcache/cache-updates/#invalidating-entities

**Describe the solution you'd like**
An option to automatically call invalidate on mutation based on __typename:
```
cache.invalidate({
  __typename: 'Todo',
  id: args.id, // could be args.id or res.id
});
```

**Comment by sarink** [comment]
If you want to refetch every time, you are probably better off using the document cache, rather than graphcache. This addition wouldn't make a lot of sense, imo.

**Comment by namnm** [comment]
@sarink As we found out it is already done:
https://commerce.nearform.com/open-source/urql/docs/graphcache/cache-updates/
![Screen Shot 2023-07-05 at 11 20 16](https://github.com/user-attachments/assets/34fb58ad-d2c6-4d63-b758-bdbbc28ce820)
