### ISSUE TITLE
[near-operation-file-preset] Override filename

### ISSUE THREAD

**Issue by gwesseling** [dotansimha/graphql-code-generator-community#23]
**Is your feature request related to a problem? Please describe.**

When generating files using the `near-operation-file-preset` and in our case in combination with `typescript-react-apollo` for generating hooks based on .graphql files (but presumably also in combination with other plugins with similar behavior and goals), `near-operation-file-preset` will generate files based on the file name of the base file (the .graphql file in our case). This is fine until your application uses a nested file structure relaying on index files for example:
```
user
  - user.graphql
post
   - post.graphql
````
`near-operation-file-preset` will generate in our case hook files with the following names `user.ts` and `post.ts` resulting in "ugly" imports such as `/hooks/graphql/user/user.ts`. It would be great if we could tell `near-operation-file-preset` what the name of the generated files should be similar to the `extension` option. So we can force `near-operation-file-preset` to generate files with a certain name such as `index`.

**Describe the solution you'd like**

Would be great if we could tell `near-operation-file-preset` to override the generated file name with an option similar to the `extension` option.

**Describe alternatives you've considered**

Looked if either `near-operation-file-preset` or `typescript-react-apollo` provide an option to change the file name of the generated files.

**Comment by gwesseling** [comment]
Possible implementation in PR #24

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1672933738721
