### ISSUE TITLE
[typescript-react-query] Remove pageParamKey from infinite query generation when using custom fetcher

### ISSUE THREAD

**Issue by jbreuil** [dotansimha/graphql-code-generator-community#271]
**Is your feature request related to a problem? Please describe.**

When generating with  ` addInfiniteQuery: true` and a custom fetcher, we got these kind of function generated : 
```
export const useInfiniteListBooksQuery = <
      TData = ListBooksQuery,
      TError = unknown,
    >(
    pageParamKey: keyof ListBooksQueryVariables,
    variables?: ListBooksQueryVariables,
    options?: UseInfiniteQueryOptions<ListBooksQuery, TError, TData>,
  ) => {
  return useInfiniteQuery<ListBooksQuery, TError, TData>(
    variables === undefined ? ['ListBooks.infinite'] : ['ListBooks.infinite', variables],
    metaData => useGraphQLAPI<ListBooksQuery, ListBooksQueryVariables>(ListBooksDocument, { ...variables, ...(metaData.pageParam ?? {}) })(),
    options,
  )
}
```
pageParamKey is mandatory while not being used. Is there a reason to keep it? Having to supply it for no reason is annoying and confusing for developper we limited knowledge of the api.  

**Describe the solution you'd like**

Remove pageParamKey or make it optional if there is plan to use it later.

**Describe alternatives you've considered**

The current workaround is either to just supply it or to replace the line with a regex after generation.

**Comment by saalihou** [comment]
We just wasted a few hours on this. This seems to have changed on recent versions, we were used to the old way and had to find that the `pageParamKey` was being ignored in newer versions. Is there a way to not generate the infinite query hooks with the `pageParamKey` parameter when a custom `fetcher` is supplied ? (and also make that a bit clearer in the docs)

**Comment by saihaj** [comment]
I released new version for [@graphql-codegen/typescript-react-query@5.0.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1695677511578) which should resolve this I think. If it doesn't let me know we can re-open and see what needs to be done here
