### ISSUE TITLE
graphql-request v5.2.0 now uses cjs/esm thus breaking the generated typings

### ISSUE THREAD

**Issue by efstathiosntonas** [dotansimha/graphql-code-generator-community#290]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-graphql-request

#### Description
Since `graphql-request@5.2.0` the dist folder has been removed in favor of cjs/esm

error thrown:
`TS2307: Cannot find module 'graphql-request/dist/types.dom' or its corresponding type declarations.`

and the import is:
`import * as Dom from 'graphql-request/dist/types.dom';`

ps. I'm using:
```
    "@graphql-codegen/cli": "^3.2.1",
    "@graphql-codegen/typescript-graphql-request": "^4.5.8"
```

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

1. Update graphql-request to `5.2.0`
2. Generate typings

### Expected behavior

I'd expect the 

`import * as Dom from 'graphql-request/dist/types.dom';` to be changed to ecs/esm folders instead of `dist`

### Platform

- `@graphql-codegen/*` 3.2.1
-  `@graphql-codegen/typescript-graphql-request: "^4.5.8"`

**Comment by efstathiosntonas** [comment]
cross referencing: https://github.com/jasonkuhrt/graphql-request/issues/467

**Comment by efstathiosntonas** [comment]
Issue is located here: https://github.com/dotansimha/graphql-code-generator-community/blob/890aabe2c018a39e358dca5896b2b2fd9148fd4e/packages/plugins/typescript/graphql-request/src/visitor.ts#L51

**Comment by Diluka** [comment]
any updates?

**Comment by efstathiosntonas** [comment]
fixed on `@graphql-codegen/typescript-graphql-request@5.0.0` 
https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1684417928535
