### ISSUE TITLE
CI is broken on Node 12

### ISSUE THREAD

**Issue by domdomegg** [dotansimha/graphql-code-generator-community#312]
### Describe the bug

On main, CI is broken because we use rimraf which uses a conditional chaning operator. This is only available in Node >= 14: https://node.green/#ES2020-features-optional-chaining-operator-----

I think our options here are either:
1. Drop support for Node 12. It is now end of life and not maintained, so I think this would be reasonable: https://endoflife.date/nodejs
2. Downcompile the rimraf library to remove the optional chaining operator
3. Replace the rimraf library with something else that doesn't use optional chaining

https://github.com/dotansimha/graphql-code-generator-community/actions/runs/4474891183/jobs/7863820721

### Expected behavior

As a contributor, I expected the CI on the main branch to be passing

**Comment by n1ru4l** [comment]
We already dropped support for Node.js 12 in graphql-code-generator. We should also drop it here and do a new major release. Any help is welcome! https://github.com/dotansimha/graphql-code-generator/releases/tag/release-1675419690826

**Comment by saihaj** [comment]
dropped support for node 12 in new release https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1695677511578
