### ISSUE TITLE
Dart Flutter plugin is not exporting the Pattern's for advanced configuration

### ISSUE THREAD

**Issue by MitkoTschimev** [dotansimha/graphql-code-generator-community#319]
### Which packages are impacted by your issue?

@graphql-codegen/flutter-freezed

### Describe the bug

No export of pattern functions are available

<img width="670" alt="image" src="https://user-images.githubusercontent.com/988473/228635028-49bf1921-2046-4d1a-9f96-993b66cef11b.png">

### Your Example Website or App

https://stackblitz.com/edit/github-jzk7hh?file=codegen.ts

### Steps to Reproduce the Bug or Issue

Use the newest version 3.0.2

### Expected behavior

Exports from the package for patterns are available

### Screenshots or Videos

<img width="670" alt="image" src="https://user-images.githubusercontent.com/988473/228635455-cafac8f8-969e-4cb1-9065-260c9f4fc046.png">

### Platform

- maacOS
- NodeJS: 16.15.1
- `@graphql-codegen/flutter-freezed` version(s): 3.0.2

### Codegen Config File

import type { CodegenConfig } from '@graphql-codegen/cli';

const id = FieldName.fromString('id');
...

**Comment by gabsn** [comment]
Same, makes it unusable for us...

**Comment by Parables** [comment]
> Same, makes it unusable for us...


@saihaj , @Urigo , @dotansimha and the whole team at The Guild, I am back. 
Do pardon me for my absence.

Please help me get this PR merged and released as soon as possible.

@gabsn and @MitkoTschimev , thanks for bringing this up.
