### ISSUE TITLE
graphql-request v6.0.0 no longer has "types.dom"

### ISSUE THREAD

**Issue by shadoworion** [dotansimha/graphql-code-generator-community#331]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-graphql-request

### Describe the bug

graphql-request@6.0.0 no longer has "types.dom"

```
error TS2307: Cannot find module 'graphql-request/dist/types.dom' or its corresponding type declarations.
import * as Dom from 'graphql-request/dist/types.dom';
```

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

1. Update graphql-request to 6.0.0
2. Generate typings

### Expected behavior

Not to get an error

### Platform

- OS: macOS
- NodeJS: 18.12.1
- graphql: 16.6.0
- graphql-request: 6.0.0
- @graphql-codegen/cli: 3.3.0
- @graphql-codegen/typescript: 3.0.3
- @graphql-codegen/typescript-graphql-request: 4.5.9
- @graphql-codegen/typescript-operations: 3.0.3

**Comment by shadoworion** [comment]
It's not a duplicate of this issue [#290](https://github.com/dotansimha/graphql-code-generator-community/issues/290)

In graphql-request 5.2.0 version, it doesn't exist in "graphql-request/dist" path, but exists in "graphql-request/build/cjs/" or "graphql-request/build/esm/" paths.

In the 6.0.0 version, it does not exist in a whole package...

**Comment by Diluka** [comment]
![image](https://user-images.githubusercontent.com/3766084/233817812-81fc4e22-ee35-442a-b763-03c52e8ff6f9.png)

**Comment by bartecargo** [comment]
This is a blocker for updating to TypeScript 5.x from 4.x since TypeScript 5.x is only supported in `graphql-request` 6.0.0:

https://github.com/jasonkuhrt/graphql-request/releases/tag/6.0.0

**Comment by nzbart** [comment]
This is a blocker for updating to TypeScript 5.x from 4.x since TypeScript 5.x is only supported in `graphql-request` 6.0.0:

https://github.com/jasonkuhrt/graphql-request/releases/tag/6.0.0

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1684417928535

**Comment by udeyrishi** [comment]
@saihaj I think this also affects `@graphql-codegen/typescript-react-query@4.1.0` when using `graphql-request` as the fetcher. Happy to file a new ticket if you'd prefer 😊

**Comment by saihaj** [comment]
> @saihaj I think this also affects `@graphql-codegen/typescript-react-query@4.1.0` when using `graphql-request` as the fetcher. Happy to file a new ticket if you'd prefer 😊

Yes would be great. If you want to send a PR that would be even better!
