### ISSUE TITLE
Implement clientId in typescript-vue-apollo config

### ISSUE THREAD

**Issue by swunderlich** [dotansimha/graphql-code-generator-community#362]
**Is your feature request related to a problem? Please describe.**

We use multiple apollo clients and would like to provide the clientId withIn the code generation for [vue-apollo-composable] (https://v4.apollo.vuejs.org/api/use-query.html#parameters) to keep things DRY

**Describe the solution you'd like**

A `clientId` config param

**Describe alternatives you've considered**

No response

**Additional context**

No response

**Comment by saihaj** [comment]
[@graphql-codegen/typescript-vue-apollo@4.1.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1698195675195)
