### ISSUE TITLE
C#Operations throws an error: fragmentNames.map is not a function

### ISSUE THREAD

**Issue by keremozben** [dotansimha/graphql-code-generator-community#387]
### Which packages are impacted by your issue?

@graphql-codegen/c-sharp-operations

### Describe the bug

Whenever I try to create output from a gql schema file using c-sharp-operations plugin, it throws this error: transformFragments.map is not a function. You can see this error even on the homepage of https://the-guild.dev/graphql/codegen website. Just select "C# Operations" from live examples and you can see the error.

### Your Example Website or App

https://the-guild.dev/graphql/codegen

### Steps to Reproduce the Bug or Issue

install these two
"@graphql-codegen/c-sharp": "^4.3.1",
"@graphql-codegen/c-sharp-operations": "^2.3.1"

config a simple codegen file. Here is mine.
![image](https://github.com/dotansimha/graphql-code-generator-community/assets/1444098/192deaf1-116f-4acb-92f1-bf809b7e89cd)

run this command in terminal
graphql-codegen --config codegen.ts

and you can see the error in the terminal
![image](https://github.com/dotansimha/graphql-code-generator-community/assets/1444098/ba4a3fc6-afc2-4e37-ac92-5270edfc5668)

### Expected behavior

As a user, I would expect a .cs output file contains my schema objects.

### Platform

- OS: Windows
- NodeJS: 18.5.0
- `graphql` version:16.7.1
-"@graphql-codegen/c-sharp": "^4.3.1",
-"@graphql-codegen/c-sharp-operations": "^2.3.1",

### Codegen Config File

import { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  overwrite: true,
  //debug: true,
  //verbose: true,
  //errorsOnly: true,
  schema: './schema.graphql',
  documents: ['./*.graphql', 'src/**/*.vue', 'src/**/*.ts', '!(src/**/*.generated.ts)'],
  generates: {
    /*'src/types.generated.ts': {
      plugins: ['typescript', 'typescript-operations']
    },
    'src/cs/types.generated.cs': {
      plugins: ['c-sharp']
    },*/
    'src/cs/operations.generated.cs': {
      plugins: ['c-sharp-operations']
    },
    src: {
      preset: 'near-operation-file',
      presetConfig: {
        baseTypesPath: 'types.generated.ts'
      },
      plugins: ['typescript-operations']
    }
  }
}

export default config

**Comment by saihaj** [comment]
duplicate https://github.com/dotansimha/graphql-code-generator-community/issues/379
