### ISSUE TITLE
`useSuspenseQuery` support

### ISSUE THREAD

**Issue by simPod** [dotansimha/graphql-code-generator-community#388]
### Is your feature request related to a problem? Please describe.

Add support for `useSuspenseQuery` introduced in https://github.com/apollographql/apollo-client/pull/10323

### Describe the solution you'd like

Allow to generate `useSuspenseQuery` hooks instead/additionally to current `useQuery` hooks

**Comment by saihaj** [comment]
would you like to send in a PR?

**Comment by saihaj** [comment]
Thank you @Hal-ang! [@graphql-codegen/typescript-react-apollo@4.1.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1698195675195)

**Comment by Hal-ang** [comment]
> Thank you @Hal-ang! [@graphql-codegen/typescript-react-apollo@4.1.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1698195675195)

I'm so happy~~ Thank you ☺️

**Comment by fforres** [comment]
<img src="https://media4.giphy.com/media/7WvAUvZZTRpSuudobh/giphy.gif"/>

**Comment by fforres** [comment]
Followup issue for `useBackgroundQuery` and `useReadQuery`  here https://github.com/dotansimha/graphql-code-generator-community/issues/477

**Comment by fresonn** [comment]
So, how can I disable it in config?

**Comment by vasilev-alex** [comment]
> So, how can I disable it in config?

didn't find this option, had to revert to the previous version

**Comment by gynekolog** [comment]
The workaround might be to use codemod to remove all SuspenseQuery functions and types.
[There's one](https://gist.github.com/gynekolog/5c84f6af87bcf2a1d4b623fe44a57dc0) I use.
