### ISSUE TITLE
Comments describing `legacyMode` incorrectly say default is `true`

### ISSUE THREAD

**Issue by AlanSl** [dotansimha/graphql-code-generator-community#390]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-react-query

### Describe the bug

The in-code documentation comment for the `legacyMode` config option is incorrect about the default value. [It says](https://github.com/dotansimha/graphql-code-generator-community/blob/b2ab7cbf092843c1e10d541804e4fe2a94872525/packages/plugins/typescript/react-query/src/config.ts#L111-L115):

```ts
  /**
   * @default true
   * @description If false, it will work with `@tanstack/react-query`, default value is true.
   */
  legacyMode?: boolean;
```

...but the [actual default is `false`](https://github.com/dotansimha/graphql-code-generator-community/blob/b2ab7cbf092843c1e10d541804e4fe2a94872525/packages/plugins/typescript/react-query/src/visitor.ts#L91):

```ts
      legacyMode: getConfigValue(rawConfig.legacyMode, false),
```

### Your Example Website or App

https://github.com/dotansimha/graphql-code-generator-community

### Steps to Reproduce the Bug or Issue

1. Go to https://github.com/dotansimha/graphql-code-generator-community
2. Search for `legacyMode`
3. Read the comments in `config.ts`, they don't match the actual code behaviour.

### Expected behavior

I expected the in-code comments to match the code behaviour.

### Platform

N/A (documentation bug)

**Comment by AlanSl** [comment]
PR here: https://github.com/dotansimha/graphql-code-generator-community/pull/391

**Comment by saihaj** [comment]
released [@graphql-codegen/typescript-react-query@5.0.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1695677511578)
