### ISSUE TITLE
Duplicate imports with near-operation-file and inlineFragmentTypes === 'combine'

### ISSUE THREAD

**Issue by aboks** [dotansimha/graphql-code-generator-community#406]
### Which packages are impacted by your issue?

@graphql-codegen/near-operation-file-preset

### Describe the bug

When using `@graphql-codegen/preset-near-operation-file` with `inlineFragmentTypes: combine`, multiple fragment imports to the same symbol in the same file may be generated. This happens e.g. with the following two files:

`child.ts`
```
export const UserEmailFragment = /* GraphQL */ `
    fragment UserEmail on User {
        email
    }
`;

export const UserNameFragment = /* GraphQL */ `
    fragment UserName on User {
        name
    }
`;
```

`parent.ts`
```
export const User1Fragment = /* GraphQL */ `
    fragment User1 on User {
        id
        ...UserEmail
        ...UserName
    }
`;

export const User2Fragment = /* GraphQL */ `
    fragment User2 on User {
        id
        ...UserName
    }
`;
```

against the following schema:
```
type Query {
  user(id: String!): User!
}

type User {
  id: String!
  name: String!
  email: String
}
```

### Your Example Website or App

not relevant

### Steps to Reproduce the Bug or Issue

1. Add a schema like described above
2. Add the two files `child.ts` and `parent.ts` as above
3. Configure graphql-codegen with `preset-near-operation-file`, the `typescript-operations` plugin and `inlineFragmentTypes: 'combine'` in the configuration
4. Run graphql-codegen

I will provide an reproduction case in the form of a failing test in a related PR.

### Expected behavior

I expect to only have a single import for the `UserName` fragment from the `child` types in the `parent` types. Instead I see two imports for `UserName`, one of them combined with `UserEmail`.

### Platform

- OS: Linux
- NodeJS: 18.17.1
- `graphql` version: 16.6.0
- `@graphql-codegen/near-operation-file-preset` version: 2.5.0

**Comment by saihaj** [comment]
released [@graphql-codegen/near-operation-file-preset@3.0.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1695677511578)
