### ISSUE TITLE
`typescript-vue-apollo`'s lazy query variables should be optional

### ISSUE THREAD

**Issue by FloEdelmann** [dotansimha/graphql-code-generator-community#438]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-vue-apollo

### Describe the bug

`vue-apollo`'s [lazy query](https://v4.apollo.vuejs.org/guide-composable/query.html#lazy-query) allows to specify a query and only later execute it with a returned `load` function. That load function also allows overriding the GraphQL variables for the query. In turn, the variables don't have to be specified in the original `useLazyQuery` function: https://github.com/vuejs/apollo/blob/v4.0.0-beta.11/packages/vue-apollo-composable/src/useLazyQuery.ts#L10

In `@graphql-codegen/typescript-vue-apollo` however, the `variables` parameter is not optional.

### Your Example Website or App

https://stackblitz.com/edit/github-wmnv5d?file=main.ts

### Steps to Reproduce the Bug or Issue

1. Create a GraphQL query with only non-nullable variables.
2. Generate types with `@graphql-codegen/typescript-vue-apollo`
3. The generated `useFooLazyQuery` has a required parameter `variables`.

### Expected behavior

The `variables` parameter should be optional, since the variables could be passed later into the returned `load` function. See https://stackblitz.com/edit/github-wmnv5d?file=main.ts

### Platform

- OS: Linux
- NodeJS: 18.17.1
- `graphql` version: 15.8.0
- `@graphql-codegen/typescript-vue-apollo` version: 4.0.0

### Codegen Config File

```ts
import { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: 'schema.graphql',
  documents: 'document.graphql',
  generates: {
    'types.ts': {
      plugins: ['typescript', 'typescript-operations', 'typescript-vue-apollo'],
    },
  },
};

export default config;
```

**Comment by Javey** [comment]
I'm facing the same issue.
