### ISSUE TITLE
`hasura-allow-list`:not compatible with other plugins

### ISSUE THREAD

**Issue by shoma-mano** [dotansimha/graphql-code-generator-community#441]
### Which packages are impacted by your issue?

@graphql-codegen/hasura-allow-list

### Describe the bug

Thanks for creating amazing plugin!This plugin is so useful!

With global fragments turned on, I am using this plugin with query containing multiple fragments. However, sometimes query is not allowed because fragments definition order is not the same with documents other codegen plugins generate.(I confirmed typescript-graphql-request and typed-document-node does not generate code that works with allow lists this plugin generate)

This happened by difference of how to treat global fragments, so I think this can be solved by changing

https://github.com/dotansimha/graphql-code-generator-community/blob/66b414eb8cb3020510beca385ec7f8280caf0fb0/packages/plugins/other/hasura-allow-list/src/index.ts#L34

to
```typescript
return Array.from(requiredFragmentNames).map(name => fragmentDefinitions.find(definition => definition.name.value === name));
```

Order of requiredFragmentNames should be kept.

### Your Example Website or App

https://github.com/shoma-mano/hasura-allowlist-reproduction

### Steps to Reproduce the Bug or Issue

1. clone repo
2. pnpm install
3. graphql-codegen
4. allow lists and document are generated in folder name generated.
5. confirm GetBook query in allow list.(AuthorData appears before BookData)
```yaml
- name: allowed-queries
  definition:
    queries:
      - name: GetBook
        query: |-
          query GetBook {
            book {
              ...BookData
              author {
                ...AuthorData
              }
            }
          }
          fragment AuthorData on Author {
            name
            books {
              ...BookData
            }
          }
          fragment BookData on Book {
            name
          }
```

6.confirm GetBookDocument generated by typed-document-node(AuthorData does not appear before BookData)
```typescript
// omitted
{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BookData"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Book"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"**FragmentDefinition**","name":{"kind":"Name","value":"AuthorData"}
// omitted
```
7.confirm GetBookDocument generated by typescript-graphql-request(AuthorData does not appear before BookData)
export const GetBookDocument = gql`
    query GetBook {
  book {
    ...BookData
    author {
      ...AuthorData
    }
  }
}
    ${BookDataFragmentDoc}
${AuthorDataFragmentDoc}`;

### Expected behavior

compatible with other plugins.

### Platform

- OS: [macOS]
- NodeJS: [19.9.0]
- `hasura` version: [2.34.0]
- `@graphql-codegen/cli` version: [5.0.0]
- `@graphql-codegen/hasura-allow-list` version: [3.0.0]

**Comment by saihaj** [comment]
[@graphql-codegen/hasura-allow-list@3.1.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1698195675195)
