### ISSUE TITLE
The typescript-rtk-query generator cannot be used with graphql-request v6

### ISSUE THREAD

**Issue by colinsullivan** [dotansimha/graphql-code-generator-community#448]
### Describe the bug

When using the latest version of graphql-request and `@graphql-codegen/typescript-graphql-request`, `@graphql-codegen/typescript-rtk-query` cannot also be used because it does not allow graphql-request v6 as a peer.

### Your Example Website or App

https://codesandbox.io/p/sandbox/thirsty-wu-kym2hd

### Steps to Reproduce the Bug or Issue

* Install `graphql-request`
* Install `@graphql-codegen/typescript-rtk-query`
* Peer dependency fails

To repro:

open https://codesandbox.io/p/sandbox/thirsty-wu-kym2hd

`npm install --save @graphql-codegen/typescript-rtk-query`

### Expected behavior

Expected result: typescript-rtk-query generator can be used with latest graphql-request version.

### Platform

- OS: N/A
- NodeJS: 16.17
- `graphql` version: 16.2
- `@graphql-codegen/*` version(s): 

```
"dependencies": {
    "@graphql-codegen/add": "^5.0.0",
    "@graphql-codegen/cli": "^4.0.1",
    "@graphql-codegen/typescript": "^4.0.1",
    "@graphql-codegen/typescript-operations": "^4.0.1",
    "graphql": "^16.2.0",
    "graphql-request": "^6.1.0"
  },
```

### Codegen Config File

N/A

**Comment by saihaj** [comment]
[@graphql-codegen/typescript-rtk-query@3.1.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1698195675195)
