### ISSUE TITLE
typescript-graphql-request generated code uses GraphQLError without importing it

### ISSUE THREAD

**Issue by yshrsmz** [dotansimha/graphql-code-generator-community#458]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-graphql-request

### Describe the bug

Generated code uses `GraphQLError` without importing it.

### Your Example Website or App

https://stackblitz.com/edit/github-jjt8y7?file=types.ts%3AL61

### Steps to Reproduce the Bug or Issue

Please refer to the `types.ts` in the repro.
In line 62, you can see `GraphQLError` used but no import for it.

### Expected behavior

There should be a import statement for `GraphQLError`

### Screenshots or Videos

<img width="839" alt="スクリーンショット 2023-10-19 0 54 47" src="https://github.com/dotansimha/graphql-code-generator-community/assets/654889/c81f6edf-3ecc-4351-8dcc-25b31f4c925e">

### Platform

- OS: macOS
- NodeJS: 18.18.2
- `graphql` version: 16.8.1
- `@graphql-codegen/tyepscript-graphql-request` version: 6.0.0

### Codegen Config File

```ts
import { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: 'schema.graphql',
  documents: 'document.graphql',
  generates: {
    'types.ts': {
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-graphql-request',
      ],
      config: {
        rawRequest: true,
      },
    },
  },
};

export default config;
```

**Comment by yshrsmz** [comment]
In the meantime we can use `add` plugin to prepend the import statement.

```
      plugins: [
        'typescript-operations',
        'typescript-graphql-request',
        {
          add: {
            content: [
              '/* eslint-disable */',
              `import type { GraphQLError } from 'graphql'`,
            ],
          },
        },
      ],
```

**Comment by saihaj** [comment]
[@graphql-codegen/typescript-graphql-request@6.0.1](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1698195675195)
