### ISSUE TITLE
[typescript-react-query] `useQuery` Expected 1-2 arguments, but got 3. ts(2554)

### ISSUE THREAD

**Issue by dmalament-wheelsup** [dotansimha/graphql-code-generator-community#481]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-react-query

### Describe the bug

After upgrading TanStack Query from version 4.29.7 to 5.7, and upgrading the `graphql-codegen` libraries to the latest versions as well, my generated file does not conform to the latest changes in RQ v5 regarding the arguments to `useQuery`. As a result, TypeScript is complaining about each instance of `useQuery` with `Expected 1-2 arguments, but got 3. ts(2554)`.

### Your Example Website or App

https://codesandbox.io/p/sandbox/adoring-moon-qthwf8

### Steps to Reproduce the Bug or Issue

1. Go to the CodeSandbox provided
2. Run `yarn generate`
3. Open the generated `types.ts` file
4. Notice the TypeScript error on line 75
5. 
<img width="895" alt="image" src="https://github.com/dotansimha/graphql-code-generator-community/assets/112402636/6ba39478-b13a-4584-a420-3644f2b05448">

### Expected behavior

The generated file should conform to TanStack Query's latest changes and not contain any TypeScript errors.

### Platform

- OS: macOS
- NodeJS: 18.8.0
- `graphql` version: 16.2
-   "@graphql-codegen/add": "^5.0.0",
    "@graphql-codegen/cli": "^5.0.0",
    "@graphql-codegen/typescript": "^4.0.1",
    "@graphql-codegen/typescript-graphql-request": "^6.0.1",
    "@graphql-codegen/typescript-operations": "^4.0.1",
    "@graphql-codegen/typescript-react-query": "^6.0.0",
    "@tanstack/react-query": "^5.7.0",
    "graphql": "^16.2.0",
    "graphql-request": "5.1.0" // using 5.1.0 here because of a different issue caused by 6.1.0

### Codegen Config File

import { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  schema: "schema.graphql",
  documents: "document.graphql",
  generates: {
    "types.ts": {
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-react-query",
      ],
      config: {
        fetcher: "graphql-request",
        exposeDocument: true,
        exposeQueryKeys: true,
        exposeFetcher: true,
        addInfiniteQuery: true,
      },
    },
  },
};

export default config;

**Comment by dmalament-wheelsup** [comment]
This ended up being my bad. I didn't include the new `reactQueryVersion` field in my config.ts. Adding that and setting it to `5` fixed this. However, I didn't see any documentation about this new parameter. It took reading through the [PR](https://github.com/dotansimha/graphql-code-generator-community/pull/434/files#diff-0e40fc3fdce3118ff7551a9e1fcd7216a6ec4951b18ea5d5f356999418e8383e) to discover this.

**Comment by mikebm** [comment]
Thank you for this. Had the same issue.
