### ISSUE TITLE
Fetcher: graphql-request, got error "Type error: Cannot find module 'graphql-request/dist/types.dom' or its corresponding type  declarations."

### ISSUE THREAD

**Issue by barayuda** [dotansimha/graphql-code-generator-community#501]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-operations, @graphql-codegen/typescript

### Describe the bug

I have trying to generate with script codegen.ts setup like below:
![image](https://user-images.githubusercontent.com/520463/220826860-30de7281-e8cb-4282-94fe-acf8060ab6e2.png)

And, when trying to build the project, I got an error like below:
![image](https://user-images.githubusercontent.com/520463/220826782-80b759d3-27c9-4dd1-8368-70591c3d1a67.png)

I used this version from my package.json
"graphql-request": "latest",
"@graphql-codegen/cli": "^3.2.0",
    "@graphql-codegen/client-preset": "^2.1.0",
    "@graphql-codegen/typed-document-node": "^3.0.1",
    "@graphql-codegen/typescript-graphql-request": "^4.5.8",
    "@graphql-codegen/typescript-operations": "^3.0.1",
    "@graphql-codegen/typescript-react-query": "^4.1.0",
    
 ==========================
if I use version below:
"graphql-request": "5.1.0", // <-- only stick with this version

codegen working well.

### Your Example Website or App

sorry, internal project

### Steps to Reproduce the Bug or Issue

I have trying to generate with script codegen.ts setup like below:
![image](https://user-images.githubusercontent.com/520463/220826860-30de7281-e8cb-4282-94fe-acf8060ab6e2.png)

And, when trying to build the project, I got an error like below:
![image](https://user-images.githubusercontent.com/520463/220826782-80b759d3-27c9-4dd1-8368-70591c3d1a67.png)

I used this version from my package.json
"graphql-request": "latest",
"@graphql-codegen/cli": "^3.2.0",
    "@graphql-codegen/client-preset": "^2.1.0",
    "@graphql-codegen/typed-document-node": "^3.0.1",
    "@graphql-codegen/typescript-graphql-request": "^4.5.8",
    "@graphql-codegen/typescript-operations": "^3.0.1",
    "@graphql-codegen/typescript-react-query": "^4.1.0",
    
 ==========================
if I use version below:
"graphql-request": "5.1.0", // <-- only stick with this version

codegen working well.

### Expected behavior

when generate the code from codegen, 

import { RequestInit } from 'graphql-request/dist/types.dom';

should generated:

import { RequestInit } from 'graphql-request/src/types.dom';

Because, the **dist** folder didn't generated on latest version of "graphql-request" (I mean [5.2.0-next.4](https://www.npmjs.com/package/graphql-request/v/5.2.0-next.4))

### Platform

- OS: Windows
- NodeJS: 16.19.0
- `graphql` version: 16.6.0
- 
"graphql-request": "latest",
"@graphql-codegen/cli": "^3.2.0",
    "@graphql-codegen/client-preset": "^2.1.0",
    "@graphql-codegen/typed-document-node": "^3.0.1",
    "@graphql-codegen/typescript-graphql-request": "^4.5.8",
    "@graphql-codegen/typescript-operations": "^3.0.1",
    "@graphql-codegen/typescript-react-query": "^4.1.0",

### Codegen Config File

import type { CodegenConfig } from '@graphql-codegen/cli';
import { GRAPHQL_SCHEMA } from './src/constants/env';
const config: CodegenConfig = {
  overwrite: true,
  schema: GRAPHQL_SCHEMA,
  documents: ['./src/**/*.graphql'],
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    './src/graphql/codegen/index.ts': {
      plugins: [
        'typescript',
        'typescript-operations',
        'typescript-react-query',
      ],
      config: {
        interfacePrefix: 'I',
        typesPrefix: 'I',
        skipTypename: true,
        declarationKind: 'interface',
        noNamespaces: true,
        pureMagicComment: true,
        exposeQueryKeys: true,
        exposeFetcher: true,
        withHooks: true,
        fetcher: 'graphql-request',
      },
    },
  },
};

export default config;

**Comment by Urigo** [comment]
I've moved this issue to the community repo because today we are recommending everyone to use the `client-preset` instead of `@graphql-codegen/typescript-graphql-request` and we've updated our docs accordingly:

https://the-guild.dev/graphql/codegen/docs/guides/react-vue

**Comment by jfairley** [comment]
@Urigo I gotta ask ... Why such a drastic shift in how the library works?

Frankly, I _love_ keeping my query definitions extracted into `.gql` files. I feel like it's a much better developer experience than what I'm seeing in the linked documentation. Multiline strings in TS files feels like a big step backwards. 

I do understand that the IDE recognizes it as graphql, and even `prettier` knows how to format it; I use the multiline string pattern heavily in my unit tests... But it's a lesser experience and results in bulkier code overall.

**Comment by beeman** [comment]
> @Urigo I gotta ask ... Why such a drastic shift in how the library works?
> 
> Frankly, I _love_ keeping my query definitions extracted into `.gql` files. I feel like it's a much better developer experience than what I'm seeing in the linked documentation for `client-preset`. Multiline strings in TS files feels like a big step backwards.
> 
> I do understand that the IDE recognizes it as graphql, and even `prettier` knows how to format it; I use the multiline string pattern heavily in my unit tests... But it's a lesser experience and results in bulkier code overall.

I second this, I really like having my queries live far away from the components where they are used. For me, the current workflow with graphql-request is perfect and I'd be sad to see it become unsupported/unmaintained.

**Comment by akullpp** [comment]
The "breaking" change occurred from `graphql-request` 5.1.0 to 5.2.0, pinning it works. Either codegen fixes it or someone forks the generator, the `client-preset` is not going to work out for me.

**Comment by AustinShelby** [comment]
I couldn't get the fix using **sed** working on Windows 10 so I wrote it using JavaScript.

Following dependencies:

```json
"@graphql-codegen/typescript-graphql-request": "^6.1.0",
"graphql": "^16.8.1",
"graphql-request": "^6.1.0",
"@graphql-codegen/cli": "^5.0.0",
"@graphql-codegen/typescript": "^4.0.1",
"@graphql-codegen/typescript-operations": "^4.0.1"
```

codegenFix.js
```js
const fs = require("fs");
const file = fs.readFileSync("./src/generated/graphql.ts", "utf8");
const lines = file.split("\n");
const newLines = [
  `import { GraphQLClient, RequestOptions } from "graphql-request";`,
  `type GraphQLClientRequestHeaders = RequestOptions["requestHeaders"];`,
].concat(lines.slice(2));
fs.writeFileSync("./src/generated/graphql.ts", newLines.join("\n"));
```

codegen.ts
```ts
import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  documents: "src/queries/*.graphql",
  generates: {
    "src/generated/graphql.ts": {
      plugins: [
        "typescript",
        "typescript-operations",
        "typescript-graphql-request",
      ],
    },
  },
  hooks: {
    afterAllFileWrite: ["node codgenFix.js"],
  },
};

export default config;
```

**Comment by emateu** [comment]
I have the same issue using:

```
"@graphql-codegen/typescript-graphql-request": "^6.1.0"
"graphql-request": "6.1.0"
```

Quick fix (macOS):
```ts
hooks: {
  afterAllFileWrite: [
    `sed -i '' "s/import { GraphQLClientRequestHeaders } from 'graphql-request\\/build\\/cjs\\/types';/export type GraphQLClientRequestHeaders = Headers | string\\[\\]\\[\\] | Record<string, string>/" ./src/generated/graphql.ts`
  ],
}
```
_Make sure to update the file path (`./src/generated/graphql.ts`) accordingly._

**Comment by ida29** [comment]
same

**Comment by Tjerk-Haaye-Henricus** [comment]
same here too

**Comment by RabeeAbuBaker** [comment]
I had the same issue with the following versions... 

```
    "graphql-request": "^6.1.0",
    "@graphql-codegen/typescript-graphql-request": "^6.1.0",
```
but upgrading to `"@graphql-codegen/typescript-graphql-request": "^6.2.0",` solved issue for me, the imports are now correct. 

After the upgrade, the imports went from 

```
import { GraphQLClientRequestHeaders } from 'graphql-request/build/cjs/types';
```
to 

```
type GraphQLClientRequestHeaders = RequestOptions['requestHeaders'];
```

**Comment by sanjusabu** [comment]
![image](https://github.com/dotansimha/graphql-code-generator-community/assets/76938125/45072922-f851-45b6-a5e6-55961d9b7071)
Same issue with   "graphql-request": "^7.0.1",

**Comment by sanjusabu** [comment]
![image](https://github.com/dotansimha/graphql-code-generator-community/assets/76938125/b144f3ce-85f1-4c91-abe1-4becc42315fc)
Same error for  "graphql-request": "^7.0.1",

**Comment by abhithtez** [comment]
> ![image](https://private-user-images.githubusercontent.com/76938125/340417805-b144f3ce-85f1-4c91-abe1-4becc42315fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTAzNDQsIm5iZiI6MTcxODY5MDA0NCwicGF0aCI6Ii83NjkzODEyNS8zNDA0MTc4MDUtYjE0NGYzY2UtODVmMS00YzkxLWFiZTEtNGJlY2M0MjMxNWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA1NTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYmNiYTA4MmM2MWIzZTA0OGU1MDYzNDM3NTU2YTlkNjA4NWFjMzdiYmZmZGE3ZTAxNzFkNDFkNDhiNjFkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rU0ESkxoDK-Op2lriVEfvzI1SxOFImZK2jDsBV2bUjA) Same error for "graphql-request": "^7.0.1",

Same issue. Any solution ??

**Comment by MinhQuan-21130491** [comment]
I get the error Unable to resolve "graphql-request" from "app\utils\GlobalApi.js" even though I have installed all the related libraries, please help me, 
![image](https://github.com/dotansimha/graphql-code-generator-community/assets/144221654/a491f29b-2400-41a6-a291-46ba3a1ca13d)

**Comment by ryparker** [comment]
shouldn't this issue be reopened?

Here's the error from TS
```sh
Cannot find module 'graphql-request' or its corresponding type declarations.
  There are types at '/node_modules/graphql-request/build/entrypoints/main.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'. ts(2307)
  ```

**Comment by AlansaladA** [comment]
![image](https://github.com/user-attachments/assets/16e205d4-37d6-49f5-b2af-007ca3a7a13b)

**Comment by ryparker** [comment]
For those of us who can't switch to ESM, use v6.1.0

```json
{
	"graphql-request": "^6.1.0",
}
```

**Comment by arman94** [comment]
use this will help:
- add a file.d.ts to your project root with this code:

`
declare module 'graphql-request' {
  export * from 'graphql-request/build/entrypoints/main';
}
`
- restart your typescript server

I'm using V7.1.0 btw

**Comment by SadmanYasar** [comment]
> just downgrade to 5.1.0 `npm i graphql-request@5.1.0`

This is working for me. Version 7.1.0 has this issue as well.

**Comment by wilpat** [comment]
Just encountered this and the downgrade to 5.1.0 option was what worked

**Comment by arman94** [comment]
make sure you installed the package then add a file for types in root of your project (I named it graphql-request.d.ts) with this content: 

`declare module 'graphql-request' {
  export * from 'graphql-request/build/entrypoints/main';
}

declare module 'graphql' {
  export * from 'graphql';
  export * from 'graphql/error';
  export * from 'graphql/execution';
  export * from 'graphql/gqlgen';
  export * from 'graphql/jsutils';
  export * from 'graphql/language';
  export * from 'graphql/mutations';
  export * from 'graphql/queries';
  export * from 'graphql/subscription';
  export * from 'graphql/type';
  export * from 'graphql/utilities';
  export * from 'graphql/validation';
}
`

**Comment by bmarcot** [comment]
> ![image](https://private-user-images.githubusercontent.com/21138159/354962012-16e205d4-37d6-49f5-b2af-007ca3a7a13b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzQzMTYsIm5iZiI6MTcyODYzNDAxNiwicGF0aCI6Ii8yMTEzODE1OS8zNTQ5NjIwMTItMTZlMjA1ZDQtMzdkNi00OWY1LWIyYWYtMDA3Y2EzYTdhMTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA4MDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjODdmY2E5NmVlYTFlZTkxZGM2YmMzZDdhMTQ5MDM5OTAyYzE4YjNmODMyZWZkOGFkMGY1ODY1YjE5YjFiYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ro1tqpciDzbdRlYq8p2tmjpI6zc2pAV6mYPEbIIvDTM)

I only changed my `tsconfig.json` and forgot to change the `package.json`.  Setting both fixed the issue.

**Comment by qumberrizvi** [comment]
This issue persists on graphql-request version ^7.1.2.

> TS2307: Cannot find module 'graphql-request/dist/types.dom' or its corresponding type declarations.

on

> import type { RequestInit } from 'graphql-request/dist/types.dom';

In the generated file.

**Comment by cabrador** [comment]
> I'm getting the same error. I'm sharing my hack here in case this is helpful to anybody.
> 
> Versions: "@graphql-codegen/cli": "^5.0.0", "@graphql-codegen/typescript": "^4.0.1", "@graphql-codegen/typescript-graphql-request": "^5.0.0", node: v18.17.1 "typescript": "5.2.2"
> 
> OS: Mac 13.3
> 
> Hook added in codegen.ts
> 
> ```
> hooks: {		
>     afterOneFileWrite: ["sed -i '' -e '1s|.*|import type { GraphQLClient, RequestOptions } from \"graphql-request\";|' -e '2s|.*|type GraphQLClientRequestHeaders = RequestOptions[\"requestHeaders\"];|' src/lib/graphql/generated.ts"]
> },
> ```
> 
> That replaces the first two lines with
> 
> ```
> import type { GraphQLClient, RequestOptions } from "graphql-request";
> type GraphQLClientRequestHeaders = RequestOptions["requestHeaders"];
> ```
> 
> That might not be the solution for everybody.

This works for me

**Comment by Slonevskyi08** [comment]
The same issue in version 7.2.0
