### ISSUE TITLE
[java] generated enum arguments lack validation

### ISSUE THREAD

**Issue by optionsome** [dotansimha/graphql-code-generator-community#637]
### Which packages are impacted by your issue?

@graphql-codegen/java

### Describe the bug

Reading in arguments with generated types crashes due to enum arguments lacking null validation.

### Your Example Website or App

https://stackblitz.com/edit/github-val3pw

### Steps to Reproduce the Bug or Issue

1. Create an input type with with an enum field and some other field(s)
2. Generate types for the query
3. Create query where the enum field is not provided but some other fields are
4. Try creating a new instance of query arguments with the graphql-java DataFetchingEnvironment from the query

### Expected behavior

Creating a new instance of query arguments should not crash if some field is not defined in the arguments provided in an incoming query.

### Platform

- OS: Linux
- NodeJS: v16.20.2
- `graphql` version: 16.8.1
- `@graphql-codegen/java` version(s): 4.0.0

### Additional context

The code crashes because it tries to call enum's `valueOf` method with a null value.

**Comment by saihaj** [comment]
[released @graphql-codegen/java@4.0.1](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1708710243852)
