### ISSUE TITLE
@graphql-codegen/typescript-rtk-query to allow import name different to api

### ISSUE THREAD

**Issue by DominicGBauer** [dotansimha/graphql-code-generator-community#68]
**Is your feature request related to a problem? Please describe.**

If I for example I name my `api` as something besides `api` e.g

```
export const graphqlApi = createApi({
  baseQuery: graphqlBaseQueryWithAuth,
  endpoints: () => ({}),
})
```

the codegen will create:

```
import { api } from '../baseApi'
```

and I would need to edit the import manually to the correct import of 

```
import { graphqlApi } from '../baseApi'
```

**Describe the solution you'd like**

Allow the import to be editable.

So in my example, I would like some functionality to allow me to edit the import name used to be editable from `api` to `graphqlApi`

**Comment by DominicGBauer** [comment]
Made a PR for this https://github.com/dotansimha/graphql-code-generator-community/pull/75

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1675282344073

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1676403866049
