### ISSUE TITLE
flutter-freezed is generating enums with a missing `,` at the ned of each prop

### ISSUE THREAD

**Issue by MitkoTschimev** [dotansimha/graphql-code-generator-community#71]
### Which packages are impacted by your issue?

@graphql-codegen/flutter-freezed

### Describe the bug

flutter-freezed is generating enums with a missing `,` at the end of each prop

<img width="502" alt="image" src="https://user-images.githubusercontent.com/988473/214774880-6e04566b-1077-4394-8a48-d7f40845547c.png">

### Your Example Website or App

private enterprise repo sorry

### Steps to Reproduce the Bug or Issue

1. Use a schema with enums
2. check the generated code with missing `,`

### Expected behavior

Every property has a trailing comma

```dart
enum ImprintOrder {
  @JsonKey(name: 'provider_ASC')
  providerAsc,
  @JsonKey(name: 'provider_DESC')
  providerDesc,
  @JsonKey(name: 'sys_firstPublishedAt_ASC')
  sysFirstPublishedAtAsc,
  @JsonKey(name: 'sys_firstPublishedAt_DESC')
  sysFirstPublishedAtDesc,
  @JsonKey(name: 'sys_id_ASC')
  sysIdAsc,
  @JsonKey(name: 'sys_id_DESC')
  sysIdDesc,
  @JsonKey(name: 'sys_publishedAt_ASC')
  sysPublishedAtAsc,
  @JsonKey(name: 'sys_publishedAt_DESC')
  sysPublishedAtDesc,
  @JsonKey(name: 'sys_publishedVersion_ASC')
  sysPublishedVersionAsc,
  @JsonKey(name: 'sys_publishedVersion_DESC')
  sysPublishedVersionDesc,
  @JsonKey(name: 'title_ASC')
  titleAsc,
  @JsonKey(name: 'title_DESC')
  titleDesc,
}
```

### Screenshots or Videos

<img width="502" alt="image" src="https://user-images.githubusercontent.com/988473/214775132-5f77a61e-1484-43a6-913f-21c6fec92abf.png">

### Platform

- OS: macOS
- NodeJS: 16.15.1
- `graphql` version: ^16.5.0
- `@graphql-codegen/*` 2.16.4

### Codegen Config File

import { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  schema: [
    {
      'https://graphql.contentful.com/content/v1/spaces/SPACE_ID/environments/dev': {
        headers: {
          Authorization: `Bearer ${process.env.CONTENTFUL_API_TOKEN}`,
        },
      },
    },
  ],
  generates: {
    'lib/domain/app_models.dart': {
      plugins: ['flutter-freezed'],
      config: {
        camelCasedEnums: true,
      },
    },
  },
};
export default config;

**Comment by MitkoTschimev** [comment]
#72 PR is fixing the issue

**Comment by Parables** [comment]
How did I miss that? Again? 🤔🧐

@MitkoTschimev Thanks for the PR.

**Comment by saihaj** [comment]
https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1675282344073
