### ISSUE TITLE
Add option to throw on duplicate operation name in named-operations-object

### ISSUE THREAD

**Issue by JonathanWbn** [dotansimha/graphql-code-generator-community#774]
**Is your feature request related to a problem? Please describe.**

The named-operations-object plugin creates an object referencing all operations by name. This gives the impression that each operation is unique and only has one definition. But there might be multiple operations defined with the same name.

**Describe the solution you'd like**

I propose adding an option to the `named-operations-object` plugin that enables throwing an error when a duplicate definition is found.

**Comment by JonathanWbn** [comment]
Opened a PR here: https://github.com/dotansimha/graphql-code-generator-community/pull/775

**Comment by saihaj** [comment]
[Released @graphql-codegen/named-operations-object@3.1.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1720714871535)
